# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bio-tm_hmm}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben J. Woodcroft"]
  s.date = %q{2011-04-06}
  s.default_executable = %q{biotm_hmm}
  s.description = %q{A bioruby plugin for interaction with the transmembrane predictor TMHMM}
  s.email = %q{donttrustben@gmail.com}
  s.executables = ["biotm_hmm"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/biotm_hmm",
    "bio-tm_hmm.gemspec",
    "lib/bio-tm_hmm.rb",
    "lib/bio/appl/tmhmm/tmhmm_runner.rb",
    "lib/bio/transmembrane.rb",
    "test/data/falciparum1.fa",
    "test/helper.rb",
    "test/test_tm_hmm_wrapper.rb",
    "test/test_transmembrane.rb"
  ]
  s.homepage = %q{http://github.com/wwood/bioruby-tm_hmm}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A bioruby plugin for interaction with the transmembrane predictor TMHMM}
  s.test_files = [
    "test/helper.rb",
    "test/test_tm_hmm_wrapper.rb",
    "test/test_transmembrane.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bio>, [">= 1.4.1"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<bio>, [">= 1.4.1"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<bio>, [">= 1.4.1"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

